### ISSUE TITLE
Title: Typo/Error in docs/tros_dev/line_follower.md

### ISSUE THREAD

**Issue by cowqer** [HorizonRDK/tros_doc#21]
Hi，I hope this message finds you well. I noticed a repeated phrase/error in one of the documentation files within the docs directory of your repository. Specifically:
File:  docs/tros_dev/line_follower.md
Section: #### 数据采集与标注
Error: The phrase "sensor提供的MIPI摄像头图像采集功能和跨设备通信能力，在PC上搭建一个简单的数据采集和标注系统。整个数据采集标注系统工作流程如下：
" is repeated twice in consecutive sentences.
Suggestion: Remove the repeated phrase .

**Comment by xuguosheng110** [comment]
ok thanks for your message，we will change this description

**Comment by zhukao** [comment]
fix with commit https://github.com/HorizonRDK/tros_doc/commit/5f86cccaf657090c09390b682e733a0263a778a3
